### ISSUE TITLE
error with make

### ISSUE THREAD

**Issue by Fish-o** [MathisLav/internetce#1]
When trying to compile the program i get the a couple of errors: 
```"[compiling C]   src/httpget.c"
C:\CEdev\examples\internettest\src\httpget.c
C:\CEDEV\INCLUDE\INTERNET.H     (149,17) :      ERROR (186) First dimension of "data" may not be omitted
C:\CEDEV\INCLUDE\INTERNET.H     (183,17) :      ERROR (186) First dimension of "data" may not be omitted
C:\CEDEV\INCLUDE\INTERNET.H     (192,20) :      ERROR (186) First dimension of "payload" may not be omitted
C:\CEDEV\INCLUDE\INTERNET.H     (217,20) :      ERROR (186) First dimension of "options" may not be omitted
C:\CEDEV\INCLUDE\INTERNET.H     (242,20) :      ERROR (186) First dimension of "options" may not be omitted
C:\CEDEV\EXAMPLES\INTERNETTEST\SRC\HTTPGET.C    (33,9) :        ERROR (108) Identifier "var_t" is not a variable or enumeration constant name
C:\CEDEV\EXAMPLES\INTERNETTEST\SRC\HTTPGET.C    (33,15) :       ERROR (128) Identifier "data" not defined within current scope
C:\CEDEV\EXAMPLES\INTERNETTEST\SRC\HTTPGET.C    (33,15) :       ERROR (100) Syntax error
C:\CEDEV\EXAMPLES\INTERNETTEST\SRC\HTTPGET.C    (33,13) :       WARNING (222) Statement has no effect
make: *** [obj/httpget.src] Error -1
```

any idea on how to fix this?
i followed your installation guide (with the help of google translate) from [here](https://tiplanet.org/forum/viewtopic.php?f=12&t=24140&p=254977#p254977)

**Comment by adriweb** [comment]
This looks like the old toolchain. You need the LLVM-based toolchain: https://github.com/CE-Programming/toolchain/wiki/Building-the-toolchain#building-the-llvm-branch

**Comment by Fish-o** [comment]
yes that did the trick, it now builds succesfully, but when i run it on my calculator and plug it in to my phone , my phone doesnt seem to view it as a device to tether with.

And on my calculator it says:
"WEB Connection..."
and then seems to hang, and i cant turn it off without pressing the reset button on the end.

**Comment by Wistaro** [comment]
> yes that did the trick, it now builds succesfully, but when i run it on my calculator and plug it in to my phone , my phone doesnt seem to view it as a device to tether with.
> 
> And on my calculator it says:
> "WEB Connection..."
> and then seems to hang, and i cant turn it off without pressing the reset button on the end.
> 
> btw isnt it insane this is about getting internet to work on a _calculator_ :p

I have the same behavior on Android 9 and 10. It's a bug with these versions.

Did you fix the problem?..

**Comment by Fish-o** [comment]
With the help of google translate I read some of his ti planet posts about it and i read about that there.
I have android 10, so I’m out of luck. I haven’t managed to fix it. I geus the only way to get this to work, without finding an old phone somewhere, as to run an emulator of some sorts on a pc with android 8.

**Comment by Wistaro** [comment]
> With the help of google translate I read some of his ti planet posts about it and i read about that there.
> I have android 10, so I’m out of luck. I haven’t managed to fix it. I geus the only way to get this to work, without finding an old phone somewhere, as to run an emulator of some sorts on a pc with android 8.

I'm not sure that emulating usb tethering is possible. 
I guess that the USB controler in your pc only works as an host, and cannot be configure to be a slave.

We juste have to wait until @MathisLav find a fix to this...
