### ISSUE TITLE
InternetCE does not work with recent smartphones

### ISSUE THREAD

**Issue by MathisLav** [MathisLav/internetce#4]
No less! The USB communication cannot establish between the calculator and any recent smartphone.  
Indeed, InternetCE worked with my old phone and some others that, apparently, were old enough. But with newer phones, the latter briefly detects the calc, but do not start any USB exchange.

This may be due to a too low voltage, maybe the power that the calculator can provide is too low to start an exchange with a phone. Or maybe this is due to a software update between android 5 and at least android 8 that has changed the way a phone starts a USB communication.

A last possibility would be that USB C behaves differently from the old micro USB ports. But this doesn't make much sense as the USB C specifications are fully backward compatible with the old USB cables.

Anyway, if anyone has any clue about this, his help would be very appreciated.

**Comment by adriweb** [comment]
Maybe @jacobly0 / @commandblockguy / @mateoconlechuga have an idea...

**Comment by MathisLav** [comment]
Ok so to sum up the two problems:
- the first one is related to the power needed by the phone I guess: it may not be fixable but it should work with a phone at least 50/60% charged.
- the second problem with new phones (or maybe "some phones") lied on the way the USB descriptor was retrieved. InternetCE was considering that the IN and OUT RNDIS endpoints were mirrored so if it found an endpoint at 0x81, it was assuming the OUT endpoint was at 0x01 which is NOT always the case.

I'll merge the branch into master once I have something more stable.

**Comment by MathisLav** [comment]
Fixed in local, I'll push as soon as possible. So, closing the issue.
