### ISSUE TITLE
When connecting the calculator to a host, InternetCE crashes

### ISSUE THREAD

**Issue by MathisLav** [MathisLav/internetce#5]
Pretty straightforward. When connecting the calculator to a host, InternetCE crashes.

In particular, it happens when we connect the calculator to a PC (with a mini USB type B / USB A cable).

**Comment by ItsSven64** [comment]
Is there progression here?
I uploaded the INTERNET script, and wiped my RAM lol

**Comment by MathisLav** [comment]
Yup, actually there's a branch I created a few days ago (fix_recent_phones I think?). You can start up with it. Additionally I'm reworking the lib so it is more stable, but I don't know when I will release it.

**Comment by MathisLav** [comment]
This is fixed in local, I'll push this for the next release. Closing the issue.
