### ISSUE TITLE
Does this require a phone, or can I use anything else?

### ISSUE THREAD

**Issue by Anonymous3-a** [MathisLav/internetce#6]
My phone recently got soft-bricked, and I want to at least set up an ssh terminal, but this doesn't say if I can use anything else. Got any ideas for something I can connect this to?

**Comment by MathisLav** [comment]
InternetCE can be used with any RNDIS-handling device (ie with an USB tethering feature). Unfortunately, smartphones are the only wide spread devices that handle RNDIS.

You could, however, use a Raspberry Pi instead of your smartphone.
