### ISSUE TITLE
USB communication!

### ISSUE THREAD

**Issue by ItsSven64** [MathisLav/internetce#7]
Awesome project man! 

How did you do USB communication? I want to send some data to a rasp pi and basically couldn't.
Do you have tips or solutions?

Many thanks
Sven

**Comment by MathisLav** [comment]
Moreover, you can find examples of how to use these two libs here: https://github.com/CE-Programming/toolchain/tree/master/examples/library_examples

**Comment by ItsSven64** [comment]
Wow, didn't think you would respond! Thanks so much for your response!
